[project]
name = "protocols"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
maintainers = [{ name = "Airalogy Team" }]
requires-python = ">=3.13"
dependencies = [
    "airalogy==0.0.13",
    "openai>=2.14.0",
]
