[airalogy_protocol]
id = "meeting_notes_en"
version = "0.0.2"
name = "Meeting Notes"
description = "A general-purpose meeting notes template for everyday meetings across teams and projects."
authors = [
    { name = "YANG Zijie", email = "yangzijie@westlake.edu.cn", airalogy_user_id = "airalogy.id.user.yangzijie" },
]
maintainers = [
    { name = "YANG Zijie", email = "yangzijie@westlake.edu.cn", airalogy_user_id = "airalogy.id.user.yangzijie" },
]
disciplines = ["Project Management", "Team Collaboration", "Productivity"]
keywords = ["meeting notes", "team collaboration", "project management"]
license = "Apache-2.0"

