[airalogy_protocol]
id = "meeting_notes_zh"
version = "0.0.3"
name = "会议记录"
description = "通用的日常会议记录模板，适用于各种团队和项目。"
authors = [
    { name = "杨子杰", email = "yangzijie@westlake.edu.cn", airalogy_user_id = "airalogy.id.user.yangzijie" },
]
maintainers = [
    { name = "杨子杰", email = "yangzijie@westlake.edu.cn", airalogy_user_id = "airalogy.id.user.yangzijie" },
]
disciplines = ["项目管理", "团队协作", "生产力"]
keywords = ["会议记录", "团队协作", "项目管理"]
license = "Apache-2.0"
